### ISSUE TITLE
Workflow about code generation in CubeAI

### ISSUE THREAD

**Issue by trieu1162000** [Flora233333/Deploy-SSD-ON-STM32#1]
Hi @Flora233333 , thanks for your wonderful project.

I would like to ask about the process of code generation when porting the model in CubeAI.
In my side, when I apply my model in STM32 Cube IDE with CubeAI packet. I dont see any the function or workflow of codes relating to, for example, pre-process input, process data, network, pos-process output, etc... like yours. Then, would you mind if you can share about how to create your code changes or explain in details what steps need to do to process the applied model.

Many thanks in advance.

**Comment by Flora233333** [comment]
Hello! @trieu1162000 ,

After adding the X-CUBE-AI (ver 9.1.0) component via CubeMX and generating the code. A file named `./X-CUBE-AI/App/app_x-cube-ai.c` will be automatically generated. This file contains the AI processing workflow generated by the system, which looks something like this:


![QQ截图20241116155948](https://github.com/user-attachments/assets/80538ff2-6cb9-43e7-a15a-0bf8aecbf4fe)


It includes the entire workflow [ init model → run(preprocess → infer → postprocess) ]. You only need to add the corresponding processing code based on your own model.

These workflow codes are automatically generated without need to select any additional options. As long as you add a model, pass the analysis, and generate the code.

**Comment by trieu1162000** [comment]
I've successfully ported my model thank to your quick response @Flora233333 
Thank you so much.
